### ISSUE TITLE
IDE annotation warnings

### ISSUE THREAD

**Issue by zek** [liaoliao666/react-query-kit#11]
I'm not using typescript however PhpStorm gives some annotation warnings such as.

I'm not sure if this is normal.

<img width="683" alt="image" src="https://user-images.githubusercontent.com/3463291/213526306-9f55ade6-890e-4ba5-936e-b8ed802f92fd.png">

<img width="1047" alt="image" src="https://user-images.githubusercontent.com/3463291/213526876-fb5ea56d-4517-4c5c-b471-1747b3c8e921.png">

**Comment by liaoliao666** [comment]
fixed in the below version
https://github.com/liaoliao666/react-query-kit/releases/tag/1.3.3
