### ISSUE TITLE
Cannot be used in Taro H5

### ISSUE THREAD

**Issue by QingYuanO** [liaoliao666/react-query-kit#13]
![image](https://user-images.githubusercontent.com/42159029/221777133-39b51a03-4467-4862-9340-3ab8d1f61678.png)
![image](https://user-images.githubusercontent.com/42159029/221777170-2c8fddc1-1143-4373-a4c4-b6b0f41cefc5.png)

**Comment by liaoliao666** [comment]
很遗憾这不是 `react-query-kit` 的问题，我 clone 了下你的仓库下来想帮你调试但发现运行不了。以下我只能从我猜测的角度给你提供帮助
- 或许 packageA 也应该包裹一个 `QueryClientProvider`, 我不是很确定 `Taro` 不同 package 是否公用一个 js 环境。
- 或许你可以测试一下不使用 `react-query-kit` 而只是使用 `@tanstack/react-query` 是否有问题，再去排查

另外再提供个建议是 `primaryKey` 不推荐使用 Function.name 作为key，打包后很可能会将函数名压缩从而可能导致与其他key冲突

**Comment by QingYuanO** [comment]
> 很遗憾这不是 `react-query-kit` 的问题，我 clone 了下你的仓库下来想帮你调试但发现运行不了。以下我只能从我猜测的角度给你提供帮助
> 
> * 或许 packageA 也应该包裹一个 `QueryClientProvider`, 我不是很确定 `Taro` 不同 package 是否公用一个 js 环境。
> * 或许你可以测试一下不使用 `react-query-kit` 而只是使用 `@tanstack/react-query` 是否有问题，再去排查
> 
> 另外再提供个建议是 `primaryKey` 不推荐使用 Function.name 作为key，打包后很可能会将函数名压缩从而可能导致与其他key冲突
感谢回复，我测试了下，在h5中使用`@tanstack/react-query`是没有问题的，然后我又在小程序环境中中测试了下，发现是可以使用`react-query-kit`，可能是taro h5环境有问题

**Comment by liaoliao666** [comment]
如果 ReactQuery 没有问题会很奇怪，因为 `react-query-kit` 并没有做任何其他额外的事情相较于直接使用 ReactQuery.
或许你可以提供一个可以正常运行的 demo 让我可以调试。目前你的 taro 项目运行会有以下报错
<img width="987" alt="Screenshot 2023-02-28 at 17 15 29" src="https://user-images.githubusercontent.com/26479949/221807374-7b55d714-ad81-44cb-af85-787aea2c2167.png">

**Comment by QingYuanO** [comment]
> 如果 ReactQuery 没有问题会很奇怪，因为 `react-query-kit` 并没有做任何其他额外的事情相较于直接使用 ReactQuery. 或许你可以提供一个可以正常运行的 demo 让我可以调试。目前你的 taro 项目运行会有以下报错 <img alt="Screenshot 2023-02-28 at 17 15 29" width="987" src="https://user-images.githubusercontent.com/26479949/221807374-7b55d714-ad81-44cb-af85-787aea2c2167.png">

https://github.com/QingYuanO/reat-query-kit-test

**Comment by QingYuanO** [comment]
> 更新到 1.3.7 应该就好了

好像还是不行耶

**Comment by liaoliao666** [comment]
你把 taro 的 prebundle 缓存清了再试试

**Comment by QingYuanO** [comment]
> 

清除也不行

**Comment by QingYuanO** [comment]
> 你把 taro 的 prebundle 缓存清了再试试

清除也不行

**Comment by liaoliao666** [comment]
你再整个示例项目我看看吧，原来的你删了

**Comment by QingYuanO** [comment]
> 你再整个示例项目我看看吧，原来的你删了

https://github.com/QingYuanO/reat-query-kit-test没有删哦

**Comment by QingYuanO** [comment]
> 你再整个示例项目我看看吧，原来的你删了

https://github.com/QingYuanO/reat-query-kit-test

**Comment by liaoliao666** [comment]
你把以下代码放到 `config/index.js` 里再试试
```js
  compiler: {
    type: "webpack5",
    // 仅 webpack5 支持依赖预编译配置
    prebundle: {
      enable: false,
    },
  },
```

**Comment by QingYuanO** [comment]
> 你把以下代码放到 `config/index.js` 里再试试
> 
> ```js
>   compiler: {
>     type: "webpack5",
>     // 仅 webpack5 支持依赖预编译配置
>     prebundle: {
>       enable: false,
>     },
>   },
> ```

加上就可以了

**Comment by liaoliao666** [comment]
那就是taro的问题了
