### ISSUE TITLE
ReturnType of query instance doesn't match actual valid return value

### ISSUE THREAD

**Issue by plrs9816** [liaoliao666/react-query-kit#14]
```typescript
export const useMarketItemQuery = createQuery<
  MarketItem,
  { id: number | undefined }
>({
  primaryKey: "/products",
  queryFn: async ({ queryKey: [primaryKey, variables] }) => {
    return (await http.post.default(`${primaryKey}/${variables.id}`)).data;
  },
  enabled: (_, { id }) => !!id,
});
```
```typescript
type a = ReturnType<typeof useMarketItemQuery>;
type b = a["data"];
// b = unknown
```
```typescript
const query = useMarketItemQuery({ variables: { id: 1 } });
type a = typeof query;
type b = a["data"];
// b = MarketItem | undefined
```

ReturnType should infer valid return type, or there should be helper type for it.
+I acknowledge that there is helper type for inferring TData, but I need the whole valid return type.

**Comment by liaoliao666** [comment]
Unfortunately the infer Type `unknown` of `data` is correct. Because the  Type`data` depends on various factors to infer. As if you pass the option `select` to ur hook that will rely on `select` to infer the type. so If u do not actually invoke this hook i can not get the correct Type for u.

**Comment by plrs9816** [comment]
Got it, thanks for quick response.
