### ISSUE TITLE
[BUG] Data type with initialData is undefined

### ISSUE THREAD

**Issue by akaguny** [liaoliao666/react-query-kit#20]
## Steps to reproduce:
1. create useAny<Response>
2. use initialData option
3. useAny in application

## Expected result:
```
const any = useAny()
------^ infered as Response type
```
## Actual result:
any is typeof Response | undefined

## Reproduce link and images:
https://codesandbox.io/s/reproduce-react-query-kit-data-type-with-initialdata-is-undefined-8f886n

### Defining
![image](https://github.com/liaoliao666/react-query-kit/assets/3505959/4da3ba4d-a47f-49a6-9657-6c410f88602c)

### Usage
![image](https://github.com/liaoliao666/react-query-kit/assets/3505959/308e1ebf-e487-4805-9f24-464689cf50d4)

## Comment:
in plain react-query initialData works as expected

```
export const usePlainTodos = ()=>{
  const result = useQuery<Todos>({
    queryKey: ["/api/data"],
  queryFn: ({ queryKey: [url] }) => axios.get(url).then((res) => res.data),
  initialData: {
    items: [],
    ts: 1
  },
  })
  const {data}= result;
  /**
   * ----^^^
   * const data: Todos
   */
}
```

**Comment by liaoliao666** [comment]
The `intiialData` may be comes from 3 way. As below

```ts
const usePost = createQuery<{ title: string; content: string }>({
  primaryKey: 'posts/:id',
  queryFn: () => fetch(`posts/1`).then(res => res.json()),
  // first way
  initialData: { title: 'post title', content: 'post content' },
  useDefaultOptions() {
    // second way
    return { initialData: { title: 'post title', content: 'post content' } }
  },
})

// third way
usePost({
  initialData: { title: 'post title', content: 'post content' },
})
```

And I also need to consider what order the `initialData` you pass. As below
```ts
const usePost = createQuery<{ title: string; content: string }>({
  primaryKey: 'posts/:id',
  queryFn: () => fetch(`posts/1`).then(res => res.json()),
  // first way
  initialData: { title: 'post title', content: 'post content' },
  useDefaultOptions() {
    // second way
    return { initialData: undefined }
  },
})

// third way
usePost({
  initialData: undefined,
})
```

It is hard to consider all kinds of the situation you may pass into. So I finally decided not to implement this feature

**Comment by markkkkas** [comment]
@liaoliao666 Would it be hard to support only third way? It would really help, since i'm pre-fetching my requests in RSC and then passing fetched data to client component.

**Comment by liaoliao666** [comment]
@markkkkas Maybe add a new util like `createSuspenseQuery` (like https://github.com/suspensive/react)  will solve ur problem

**Comment by liaoliao666** [comment]
Hi, u guys now can view the new function `createSuspenseQuery` that solve this problem.
