### ISSUE TITLE
Callbacks in mutation definition vs. inside of component

### ISSUE THREAD

**Issue by the-medo** [liaoliao666/react-query-kit#21]
Hello, I would like to use onSuccess callback from both mutation definition and hook in component. So I have something like this:

Mutation definition:
```ts
export const useUploadImage = createMutation({
  mutationFn: async (variables: ExpandedUploadImageRequest) => ImagesCollection.uploadImage(variables),

  onSuccess: (data, variables) => {
    //add new image data into infinite query data (img url, guid,...)
  },
});
```

Component:
```ts

const Component: React.FC = () => {
  const uploadImage = useUploadImage({
    onSuccess: (data) => {      //only this one is called

      // show image preview in this component
    },
  });
 //...

  const handleUpload = useCallback(() => {
    //....
    uploadImage.mutate(uploadArgs);
  }, [uploadImage, uploadArgs]);
}
```

Currently, when i call my uploadImage mutation and it succeeds, only onSuccess callback from the component is called. When I remove it, the one in mutation definition is called. 

Is there some way to call both of them? Or from inside the onSuccess in component call the "parent" one? Thanks

**Comment by liaoliao666** [comment]
You can simply put `onSuccess` in  the function `mutate` options, like below
```ts
uploadImage.mutate(uploadArgs, { onSuccess: () => {...} });
```

**Comment by liaoliao666** [comment]
or just put ur default logic in `mutationFn`, like
```
export const useUploadImage = createMutation({
  mutationFn: async (variables: ExpandedUploadImageRequest) => {
    const data = await magesCollection.uploadImage(variables)
    //add new image data into infinite query data (img url, guid,...)
    return data
  },
});
```

**Comment by the-medo** [comment]
Thanks, `uploadImage.mutate(uploadArgs, { onSuccess: () => {...} });` seems to work fine.
