### ISSUE TITLE
createQueries

### ISSUE THREAD

**Issue by emad-ms** [liaoliao666/react-query-kit#23]
Do you have any plan for `createQueries()` to support `useQueries()`?
https://tanstack.com/query/v4/docs/react/reference/useQueries

**Comment by liaoliao666** [comment]
No, I think it does not make any mean. if u wanna using queries u can simply implement as belown
```ts
const queries = useQueries({
  queries: [
    { queryKey: usePost.getKey(), queryFn: usePost.queryFn },
    { queryKey: useProjects.getKey(), queryFn: useProjects.queryFn },
  ],
})
```

**Comment by emad-ms** [comment]
Makes sense. Thanks
