### ISSUE TITLE
setData and middleware

### ISSUE THREAD

**Issue by denisborovikov** [liaoliao666/react-query-kit#27]
Hi there,

The latest middleware update is an excellent addition to the library. Do you think it makes sense to remove `setData` from the library API because the end user can implement it using middleware?

**Comment by liaoliao666** [comment]
Actually I want to remove all APIs such as `setData`, `enabled`, `queryKey` and `variables` etc. But I'm not sure this changes too much for previous users.

**Comment by denisborovikov** [comment]
You can release it as a breaking change as a new major version.

**Comment by liaoliao666** [comment]
Thanks for the advice that allowed me to stick with my thoughts on this change. This change is available in 2.0.0
https://github.com/liaoliao666/react-query-kit/releases/tag/2.0.0
