### ISSUE TITLE
Make expose methods available in middleware

### ISSUE THREAD

**Issue by denisborovikov** [liaoliao666/react-query-kit#28]
Hi! Thanks for the new version. The middleware is an excellent idea and provides many additional opportunities.

I'm experimenting with new middleware and trying different hypothetical scenarios. I want to enrich the hook and add a built-in `fetchQuery` method (can be any of queryClient's methods) .

```js
const { fetchQuery } = usePosts()

const handleClick = async () => {
   await fetchQuery()
   ...
}

```

The way I see it is implemented via the middleware below. The one thing is missing - It would be great to have the exposed methods available in the middleware (i.e. getKey etc). If methods would be available as an argument, the code might look like this:

```js
const fetchQueryAttacher = (useQueryNext) => {
  return (options, methods) => {  // expose methods here
    const queryClient = useQueryClient()

    const hook = useQueryNext(options)

    return Object.assign({}, hook, {
      fetchQuery: () => {
        return queryClient.fetchQuery(methods.getFetchOptions())
      },
    })
  }
}
```

What do you think?  It's still unclear how to type this, but this is a different issue.

**Comment by liaoliao666** [comment]
It is unnessesary. You can get all of exposed mehods from `options`. As beblown
```ts
import { getKey } from "react-query-kit"

const middleware = (useQueryNext) => {
  return (options) => {
    // getKey(options.priamaryKey, options.variables) equals to useSomething.getKey(options.variables)
    // getFetchOptions(options.variables) eaquals to { queryKey: getKey(options.priamaryKey, options.variables), queryFn: options.queryFn }
  }
}
```

**Comment by liaoliao666** [comment]
And u should not assign the hook result to a empty object, it wil break the behavior of the rules of [notifyOnChangeProps](https://tanstack.com/query/v4/docs/react/guides/migrating-to-react-query-4#notifyonchangeprops-property-no-longer-accepts-tracked-as-a-value). You should do it like belown.
```
Object.assign(hook, { ... })
```

**Comment by denisborovikov** [comment]
If you create a middleware for the `useSomething` hook, `useSomething.getKey` is not assigned when the middleware is executed.

Sure, we can implement `getKey`, but it can go too far, and we'll need to reimplement what's already implemented in the library instead of reusing it.

**Comment by denisborovikov** [comment]
Sure, you can use `useSomething.getKey`, but it means you can't make a universal middleware that would work with any hook. It will be explicitly attached to `useSomething` hook.

If methods were exposed as in my example, we could create a `fetchQueryAttacher` hook and add this middleware to any hook without need to change `useSomething.getKey` to `useSomethingElse.getKey`.

**Comment by liaoliao666** [comment]
I don't think there's much cost savings from reusing these exposed functions.
If in ReactQuery v5, the second parameter of the middleware has been defined as queryClient. And this feature will also break this behavior.
```ts
const middleware = (useQueryNext) => {
  return (options, queryClient) => useQueryNext(options, queryClient))
}
```

**Comment by denisborovikov** [comment]
What if you expose it as 3rd argument? The library API can be extended, and you can add more exposed methods later. Reimplementing them manually in the middleware isn't a good idea from my perspective.

**Comment by liaoliao666** [comment]
> change `useSomething.getKey` to `useSomethingElse.getKey`.

You do not need to change  `useSomething.getKey` to `useSomethingElse.getKey`.  Just simply import `getKey` from "react-query-kit" to get all `queryKey` of current useQuery. as belown.
```ts
import { getKey } from "react-query-kit"

const middleware = (useQueryNext) => {
  return (options, queryClient) => {
    // this is so simple
    const queryKey = getKey(options.primaryKey, options.variables)
  }
}
``

**Comment by denisborovikov** [comment]
Oh I didn't notice it's exported.

**Comment by liaoliao666** [comment]
> Oh I didn't notice it's exported.

poor document😂
