### ISSUE TITLE
createQueryClient function

### ISSUE THREAD

**Issue by ArturKhantsevich** [liaoliao666/react-query-kit#29]
Hello,

Readme file mentions `createQueryClient` function which should allow to register middlewares globally. The search repo [result](https://github.com/search?q=repo:liaoliao666/react-query-kit%20createQueryClient&type=code) says that there is no any such functionality defined. Do you have any plans to implement this feature?

Thank you for this great package.

**Comment by liaoliao666** [comment]
There already support  register middlewares globally but no typescript. You can simply add `@ts-ignore` to solve this problem
```
new QueryClient({
  defaultOptions: {
    queries: {
      use: [middleware],
    },
  },
})
```

**Comment by denisborovikov** [comment]
You can try this

```
import { createQuery as createQueryFactory } from 'react-query-kit'

function createQuery<Response, Variables, Error>(
  options: Parameters<typeof createQueryFactory<Response, Variables, Error>>[0]
) {
  return createQueryFactory<Response, Variables, Error>({
    ...options,
    use: [requestIdAttacher, fetchQueryAttacher, ...options.use],
  })
}

const usePosts = createQuery({ queryKey: ..., queryFn: ..., })  // has additional features from pre-defined middleware
```

**Comment by denisborovikov** [comment]
If you use default middleware using `defaultOptions` and ad middleware with `createQuery` as far as I understand, `createQuery` will replace the ones from defaults, not merge them.

**Comment by liaoliao666** [comment]
> If you use default middleware using `defaultOptions` and add middleware with `createQuery` as far as I understand, `createQuery` will replace the ones from defaults, not merge them.

It will merge them, only for middleware. Just like swr.

**Comment by denisborovikov** [comment]
Oh interesting

**Comment by liaoliao666** [comment]
doc updated.
