### ISSUE TITLE
Update `peerDependencies` config to properly accept `@tanstack/react-query` v5

### ISSUE THREAD

**Issue by snelsi** [liaoliao666/react-query-kit#33]
## Issue Description

I encountered an npm error when trying to use `react-query-kit` with `@tanstack/react-query` version `5.0.0-rc.1`. The current `peerDependencies` configuration restricts compatibility to `@tanstack/react-query` version 4.x, leading to dependency conflicts.

**Error Message:**
```plaintext
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: xcontrol-ui@2.0.0
npm ERR! Found: @tanstack/react-query@5.0.0-rc.1
npm ERR! node_modules/@tanstack/react-query
npm ERR!   @tanstack/react-query@"^5.0.0-rc.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @tanstack/react-query@">= 4.0.0" from react-query-kit@2.0.1
npm ERR! node_modules/react-query-kit
npm ERR!   react-query-kit@"^2.0.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
```

https://blog.greenkeeper.io/introduction-to-version-ranges-e0e8c6c85f0f

## Proposed Solution
To resolve this issue and allow compatibility with @tanstack/react-query version 5.x and beyond, we should update the peerDependencies configuration in react-query-kit to the following:

```
"peerDependencies": {
  "@tanstack/react-query": "^4 || ^5"
}
```

This change will permit users to use the latest version of @tanstack/react-query without encountering dependency conflicts.

**Comment by liaoliao666** [comment]
Good job. Available in v2.0.2
