### ISSUE TITLE
[bug] wrong react query version being installed

### ISSUE THREAD

**Issue by emmanuelchucks** [liaoliao666/react-query-kit#37]
I'm using tanstack query v5 rc in my project but v4 is being installed within react-query-kit and causing errors in my setup. How can I get it to install v5 as a peer dependency?

running `npm ls --all` gives this
```
└── react-query-kit@2.0.5/
    └── @tanstack/react-query@4.36.1/
        └── @tanstack/query-core@4.36.1
```

**Comment by liaoliao666** [comment]
ReactQuery v5 is not released. But you can install the `rc` version with `yarn add @tanstack/react-query@rc`

**Comment by emmanuelchucks** [comment]
### Using npm
1. `npm i @tanstack/react-query@rc`
2. `npm i react-query-kit`

output:

![Screenshot 2023-10-13 at 17 09 54](https://github.com/liaoliao666/react-query-kit/assets/31349069/af66358a-ba02-40de-84b5-423646ba2cca)

### Using yarn
1. `yarn add @tanstack/react-query@rc`
2. `yarn add react-query-kit`

output:

![Screenshot 2023-10-13 at 17 55 48](https://github.com/liaoliao666/react-query-kit/assets/31349069/306b50ae-181b-4797-b41e-ed2d45b52462)

3. `npm ls -all`

output:

![Screenshot 2023-10-13 at 17 47 08](https://github.com/liaoliao666/react-query-kit/assets/31349069/3e2d495d-174c-4302-a54f-1b4ed41c59fc)

### Context
I'm actually using bun to install packages. This issue came up after upgrading to v1.0.6 which now installs peer deps by default. It silently installed @tanstack/react-query@4.36.1.

Setting this in my `bunfig.toml` fixes the issue.
```toml
[install]
peer = false
```

If you don't want to pursue this further, feel free to close this issue. 

P.S: Thank you for working on this library, I can't imagine using Tanstack Query without it.

**Comment by liaoliao666** [comment]
I'm not sure why bun automatically installs @tanstack/react-query@4.36.1.
Maybe I can make "@tanstack/react-query" optionally installable via "peerDependencyMeta" to solve this problem?

```json
{ 
 "peerDependencies": {
       "@tanstack/react-query": "^4 || ^5"
  }
  "peerDependenciesMeta": {
    "@tanstack/react-query": {
      "optional": true
    }
  }
```

**Comment by emmanuelchucks** [comment]
Yeah if that will fix the issue, please do. Thanks again

**Comment by emmanuelchucks** [comment]
If it'll solve it then yes please.

**Comment by emmanuelchucks** [comment]
On a second thought, this might be a bug with bun: https://github.com/oven-sh/bun/issues/6445

**Comment by danielpza** [comment]
I cannot reproduce this issue. With yarn I get the correct react query version:

```sh
❯ yarn add @tanstack/react-query@rc
❯ yarn add react-query-kit
❯ yarn why @tanstack/react-query   
└─ react-query-kit-issues-37@workspace:.
   └─ @tanstack/react-query@npm:5.0.0-rc.12 [8c5a9] (via npm:^5.0.0-rc.12 [8c5a9])
```

Using yarn berry

**Comment by emmanuelchucks** [comment]
@danielpza I used yarn v1 (classic) in the above test.

**Comment by liaoliao666** [comment]
@emmanuelchucks Now you can install `beta` version using `yarn add react-query-kit@beta` to test whether it works.

**Comment by emmanuelchucks** [comment]
@liaoliao666 Unfortunately, it didn't fix the issue. It really might be an issue with bun.
