### ISSUE TITLE
What's the difference between primaryKey and queryKey?

### ISSUE THREAD

**Issue by franciscohanna92** [liaoliao666/react-query-kit#41]
Hi there! I was trying out `react-query-kit` to see if we can adopt it at work, but had a hard time understanding what's the difference between RQK's `primaryKey` and RQ's `queryKey`, and why the former does not admit an array as the latter.

Why is this?

**Comment by liaoliao666** [comment]
It will break the rules of the `variables` would be the second element in the `queryKey` when you pass an array key into `createQuery`. Then There is a mental burden of which element is `variables` when you wanna get `variables` form `queryKey` as belown.

```ts
createQuery({
  primaryKey: ['a'],
  queryFn: ({ queryKey: [_a, variables] }) => {}
})

createQuery({
  primaryKey: ['a', 'b'],
  queryFn: ({ queryKey: [_a, _b, variables] }) => {}
})
``

**Comment by liaoliao666** [comment]
Now ReactQueryKit v3 version can support `queryKey`, you can experience it through the command `yarn add react-query-kit@beta`. And the docs here: https://github.com/liaoliao666/react-query-kit/tree/v3#readme.
