### ISSUE TITLE
Add default `select` to `createQuery`

### ISSUE THREAD

**Issue by debater-coder** [liaoliao666/react-query-kit#8]
This will allow a user to pass a [select](https://tanstack.com/query/v4/docs/react/reference/useQuery#:~:text=select%3A%20(data%3A%20TData)%20%3D%3E%20unknown) option to `createQuery` that will be passed to `useQuery`.

**Comment by liaoliao666** [comment]
This results in the inability to infer the Type `Data` if pass select to `createQuery`. If u wanna  select the data i would prefer to do it like below.
```js
type Data = { title: string; content: string }

const usePost = createQuery<Data>(...)

function selectPostTitle(data?: Data) {
  return data?.title
}

function APP() {
  const { data: title } = usePost({ select: selectPostTitle })
}
```
